project:
  type: book
  output-dir: docs

execute:
  freeze: auto

book:
  title: "医学英語：臨床論文の読み方"
  author: "馬場 美彦"
  date: today
  chapters:
    - index.qmd
    - design.qmd
    - frailty.qmd
    - part: meta.qmd
      chapters:
        - meta_intro.qmd
    - part: ct.qmd
      chapters:
        - rct_intro.qmd
    - part: observation.qmd
      chapters:
        - crosssectional_intro.qmd
        - cohort_intro.qmd
    - part: critical.qmd
      chapters: 
        - protocol.qmd
        - statement.qmd
        - letter.qmd
    - summary.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: style.css
    grid:
      margin-width: 350px

reference-location: margin
citation-location: margin

website:
  site-url: "https://babayoshihiko.github.io/How/" # makes site links work on your remote site

