project:
  type: website

website:
  title: "How"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid:
      margin-width: 350px

  pdf: default

reference-location: margin
citation-location: margin
