# 縦断研究  {#sec-cohort-intro}

```{r include=FALSE}
# Do nothing
```

## キーワード {#sec-cohort-keyword}

縦断研究 (longitudinal study) とは、一定期間にわたって継続的に観察する研究手法です。

縦断研究には、現時点から始める「前向き (prospective) コホート研究」と、過去のデータにさかのぼる「後ろ向き (retrospective) コホート研究」があります。

両者には以下のような違いがあります。

| | 前向き | 後ろ向き |
| - | ---- | -------- |
| 解析の時期 | データがそろってから解析 | データがあればすぐに解析可能 | 
| 変数 |  あらかじめ設定することで取り忘れがなくなる | 観測していない変数には対応できない |
| 対象疾患 | 有病率の高い疾患に適する | 稀な疾患に適する |


後ろ向きコホート研究 (ケース・コントロール研究とも呼ばれる) は、アウトカム (病気など) の有無で対象者を分け、過去にさかのぼって要因への曝露を調査するため、因果関係の証明は困難ですが、短期間・低コストで珍しい病気の研究に適しています。ただし、データの質や交絡因子の影響を受けやすく、因果関係と解釈するには他の研究との総合的な判断が必要不可欠です

前向きコホート研究は、特定の要因 (曝露) を持つ集団と持たない集団を未来に向かって長期的に追跡し、両者の間で将来発生する疾患などの違いを観察・比較することで、要因と結果の「因果関係」の強さや可能性を推定する強力な観察研究手法です。ランダム化比較試験 (RCT) には及ばないものの、時間的な前後関 (曝露が先、発症が後) が明確で、交絡因子を調整できれば因果関係に迫ることができ、特に生活習慣病や環境要因と疾患の関係解明に貢献しています

### Kaplan-Meier 曲線

後述する log-rank 検定 や Cox 比例ハザードモデル (ハザード比) と組み合わせて用いられる図は、Kaplan-Meier 曲線です。

曲線が下に下がっていくほどイベントが発生したことを意味し (上向の場合も同様)、傾きがハザード (瞬間的なリスク) を表します。

### log-rank 検定

log-rank 検定は、2 つ以上の群の生存曲線の差を検定します。

### ハザード比

Cox 比例ハザードモデルは、一定期間内のイベントの発生の有意差を検定します。

- 例 1: ある病気にかかった人とかかっていない人の、一定期間内の死亡率の差を検定
- 例 2: 研究開始時点で頑健な人たちが、一定期間内にフレイルになるかならないかを検定

共変量それぞれについて、相関（または因果）関係の大きさをハザード比（Hazard Ratio, HR）で表します。これは、リスク比とおおむね同じように扱うことが可能です。さらに、交絡因子で調整することもできます。なお、正確には、人-時間あたりのイベント率です。

比較的解釈しやすいハザード比ですが、ハザード比 2.0 を誤って「2.0倍早い」と解釈することがあります [@spruance2004hazard]。ハザード比が 1 より大きいので「より早い」のは確かですが、それが 2.0 倍とは限りません。

### 論文の例

フレイル

- Kennard A, Richardson A, Rainsford S *et al.* (2024). Longitudinal frailty assessment in the prediction of survival among patients with advanced chronic kidney disease: a prospective observational single-centre cohort study. *Bmj Open*, 14(10), e087189.

認知症

- Gallagher J, Gochanour C, Caspell-Garcia C, *et al.* & Parkinson's Progression Markers Initiative. (2024). Long-term dementia risk in Parkinson disease. Neurology, 103(5), e209699.