# Liu W (2020)  {#crosssectional-liu}

## 論文

それでは、いよいよ横断研究の論文を読みましょう。

Liu W, Puts M, Jian F, Zhou C, Tang S and [Chen S](https://seeds.office.hiroshima-u.ac.jp/profile/ja.37a092b9162a37f6520e17560c007669.html) (2020) Physical frailty and its associated factors among elderly nursing home residents in China

- 中南大学湘雅护理学院, China
- Lawrence S. Bloomburg Faculty of Nursing, U of Toronto, Canada
- 湖南師範大学医学院, China
- 九州大学

Corresponding author の所属先や ORCID は、サイト上のどこで確認できるか？

論文は、こちらにあります。

https://doi.org/10.1186/s12877-020-01695-5

Creative Commons Attribution 4.0 International License

## 用語

prevalence は有病率のことですが、フレイルは病気ではないため、有症率やフレイル率などと訳されます。

患者は、住む場所に応じて 3 つに分類されます。タイトルから、これは “nursing home” であることがわかりますが、これは一般的には施設に該当します。なお、nursing home は、国による違いが大きく、高齢者専門ジャーナル JAMDA は、アメリカの nursing home は施設ではないとしています。この論文は中国の研究なので、施設で良いでしょう。

- community-dwelling patients 地域在住患者
- institutionalized patients 施設入所患者
- hospitalized patients 入院患者

comorbidity: 重複疾患

cut-off (points): スクリーニング検査等の基準値。カットオフ値。

## Abstract

まず最初に Abstract を読みましょう。

::: {.panel-tabset}
## 原文  {.unnumbered}

**Background** Evidence is scarce on the trend in prevalence of physical frailty in China; the primary purpose of this study was to identify the prevalence and correlates of physical frailty among older nursing home residents in China.

## 日本語訳   {.unnumbered}

- 中国の施設在住高齢者のフレイル率はまだエビデンスがない
:::

::: {.panel-tabset}
## 原文  {.unnumbered}

**Methods** Cross-sectional study in 20 nursing homes in Changsha, China. Physical frailty was defined based on the frailty phenotype including weight loss, low grip strength, exhaustion, slow gait speed, and low physical activity. Participants with at least three affected criteria were defined as being frail. Participants with one or two affected criteria were considered as pre-frail, and those with no affected criteria were considered as robust. A total of 1004 nursing home residents aged 60 and over were included in this study. A multinomial logistic regression model was used to analyze the associations of physical frailty with its potential risk factors, including age, sex, education levels, marital status, type of institution, living status, current drinking, current smoking, regular exercise, and self-reported health.

## 日本語訳   {.unnumbered}

- 中国の長沙市の20の老人ホームで調査
- 老人ホーム在住者で60歳以上の1004名
- 多項ロジスティック回帰で関連因子を調査
:::

::: {.panel-tabset}
## 原文  {.unnumbered}

**Results** The overall prevalence of physical frailty and prefrailty was 55.6, and 38.5%, respectively. The rate of physical frailty substantially increased with age, and was higher in women than in men (69.5% vs. 30.5%). The multinomial logistic regression analysis showed that older age, being women, living in a private institution, living alone or with unknown person, having no regular exercise (≤ 2 times/week), and poor self-reported health were significantly associated with increased odds of being physically frail.

## 日本語訳   {.unnumbered}

- フレイル率は55.6%、プレフレイル率は38.5%
- フレイルは、年齢、性別、私立老人ホーム、一人暮らし、運動習慣、自己報告不健康と関連
:::

::: {.panel-tabset}
## 原文  {.unnumbered}

**Conclusion** We demonstrated physical frailty is highly prevalent among older residents in nursing homes in China, especially in women. The potential role of those associated factors of physical frailty warrant further investigations to explore their clinical application among elderly nursing home residents.

## 日本語訳   {.unnumbered}

- フレイル率は55.6%、プレフレイル率は38.5%
- フレイルは、年齢、性別、私立老人ホーム、一人暮らし、運動習慣、自己報告不健康と関連
:::

以上で、Abstract は終わりになります。通常、ロジスティック回帰の Abstract では、説明変数のオッズ比も掲載されることが多いですが、ここは掲載されていません。

では、ロジスティック回帰とはどういう解析を行うのでしょうか？Abstract によると、「多項」ロジスティック回帰とあります。これはなんでしょうか？これらは Methods で解説します。

## Background

::: {.panel-tabset}
## 原文  {.unnumbered}

… Frailty refers to a state of increased vulnerability to stressors, characterized by a decreased physiological reserves …

## 日本語訳   {.unnumbered}

increased vulnerability や、decreased physiological reserves はとても訳しづらい英語です。ただ、フレイル論文では定番のような表現でもあります。定番なので、多くの訳もあります。おおむね、このように訳されています。「フレイルとは、ストレスに対する脆弱性が亢進した状態で、生理的予備能が低下する特徴がある。」
:::

::: {.panel-tabset}
## 原文  {.unnumbered}

… two main operational approaches have been widely used to measure frailty: the frailty phenotype [5] and the Frailty Index [8]. 

## 解説   {.unnumbered}

フレイルの操作定義の方法としては、表現型[^crosssectinal-liu-phenotype]と Frailty Index という二つの方法がある、とされています。

実は、読み進めてみるとわかりますが、この研究のフレイルの判定方法は表現型です。ここでわざわざ Frailty Index を紹介する意図はわかりかねます。
:::

[^crosssectinal-liu-phenotype]: フレイルの操作定義の表現型とは何か?

第 2 段落の最後に、研究の目的が書かれています。

::: {.panel-tabset}
## 原文  {.unnumbered}

… we aimed to investigate the prevalence of physical frailty and its associated factors among older people living in nursing homes in China.

## 解説   {.unnumbered}

prevalence of physical frailty は、老人ホームにおける調査時点でのフレイルの有病率です。

associated factors は、関連する因子です。これは通常ロジスティック回帰で求め、結果はオッズ比で示されます。

以上、@sec-crosssectional-intro でみたように、典型的な横断研究になっています。
:::

## Methods

Methods では、研究の方法が書かれています。

::: {.panel-tabset}
## 原文  {.unnumbered}

… We contacted all eligible participants by sending brochures explaining the study and inviting them to participate (n = 2550), and a total of 2204 residents agreed to participate in the survey, with a response rate of 86.4%. Of those, 1607 participants who completed the baseline survey by sending brochures were included in this study (597 died or moved out of those nursing homes during the survey period). We excluded participants who had a history of dementia (n = 66), Parkinson’s disease (n = 52), stroke (n = 208), or a Mini-Mental State Examination (MMSE) score < 18 (n = 69). Also, participants with missing data on any components of physical frailty were excluded (n = 208). Therefore, the final sample included 1004 participants (339 men and 665 women) (Fig. 1).

## 解説   {.unnumbered}

通常は Results に書かれる内容です。
:::

第 2 段落では、Fried のフレイル基準を詳しく解説しています。

::: {.panel-tabset}
## 原文  {.unnumbered}

Slowness was defined as the average walk speed in a 5-m walking test. Starting from a motionless position, participants were instructed to take this test twice, and the time (seconds) of gait speed was recorded with a digital stopwatch between the 3 and 8 m in each trial. We measured the time taken (in seconds) to pass 8 m to calculate gait speed (m/s).

## 解説   {.unnumbered}

「高齢者の歩行速度は、8 m 以上歩いていただき、その中間の 3 m から 5 m の間の速度を計測しました。」

従来は16 m 程度歩いて、中間の 10 m を計測していた。
:::

::: {.panel-tabset}
## 原文  {.unnumbered}
**Correlates of physical frailty**

Information on the following covariates was collected through the questionnaire: age, sex, education level (elementary and below, or junior middle school and above), marital status (married, other [widowed, divorced, never married]), type of institution (public or private), living status (living with husband/wife, living with alone or others [unknown person]), current drinking (yes or no), current smoking (yes or no), regular exercise (≤ 2 times/week, ≥ 3 times/week), and self-reported health (very good or good, fair or poor).

## 解説   {.unnumbered}

ロジスティック回帰では、covariate (共変量) は複数設定することができます。ここでは、

- 年齢、性別、教育歴、婚姻状態
- type of institution[^crosssectional-liu-institution]
- 現在の飲酒、喫煙
- 運動習慣
- 自己報告の健康状態
- ADL (Katz scale)
- 重複疾患 (comorbidity)
:::

[^crosssectional-liu-institution]: institution の訳は何か?

